di = dict()
di['78'] = 'Data Science and Big Data Analytics'
di['79'] = 'Data Science: From Research to Application'
di['80'] = 'Probability and Simulation'
di['83'] = 'Analyzing Categorical Data'
di['83'] = 'Permutation Statistical Methods with R'
di['95'] = 'An Introduction to Statistical Data Science'
di['101'] = 'Structural Analysis'
di['103'] = 'Statistics and Analysis of Scientific Data, 3E'
di['108'] = 'An Introduction to Categorical Data Analysis, 2E'
di['110'] = 'All of Nonparametric Statistics'
di['117'] = 'An Introduction to Applied Multivariate Analysis with R'
di['119'] = 'An Introduction to Generalized Linear Models, 4E'
di['124'] = 'Applied Longitudinal Analysis, 2E'
di['124'] = 'BIOSTATISTICS A Foundation for Analysis in the Health Sciences, 9E'
di['144'] = 'Biostatistics with R'
di['163'] = 'Examples in Parametric Inference with R'
di['202'] = 'introduccion a los modelos mixtos'
di['212'] = 'An Introduction to Statistical Learning, 2E'
di['216'] = 'Statistics for Data Scientists'
di['216'] = 'Learn R for Applied Statistics'
di['224'] = 'Linear Mixed-Effects Models Using R'
di['274'] = 'Understanding Statistics Using R'
di['285'] = 'The Statistical Analysis of Functional MRI Data'
di['308'] = 'Statistics for Non-Statisticians'
di['345'] = 'The R Software'
di['348'] = 'R for Data Science'


print(di)
